### PR TITLE
Tighter permission control on the UI

### PR DESCRIPTION
**Pull request by avsdev-cw**
Prevent users/guests from accessing the "Ask Question" and "Add New FAQ" pages
(also removing the navigation links) and also prevent them from adding comments
unless they have permission to do so or guest modifications are allowed.

### CODE REVIEW

**Comment by thorsten** [comment]
This is awesome, but a BC break for 2.9. I would love to add this into 2.10, would it be possible for you to add this PR against the 2.10 branch?

**Comment by avsdev-cw** [comment]
I would but I'm having real issues getting the build chain working for 2.10.  

had to drop bootstrap to the latest stable version (doesnt seem to like the beta version).  After that I used yarn instead of bower which seemed to work ok (no errors at least). 

After running grunt I get:
Running "sass:development" (sass) task
>> Error: File to import not found or unreadable: ../../../../node_modules/bootstrap/scss/bootstrap.
>>        Parent style sheet: /home/phpmyfaq/phpMyFAQ/phpmyfaq/admin/assets/scss/style.scss
>>         on line 18 of phpmyfaq/admin/assets/scss/style.scss
>> >> @import "../../../../node_modules/bootstrap/scss/bootstrap";
>>    ^
Warning:  Use --force to continue.

**Comment by thorsten** [comment]
Okay, I'll see the issues in 2.10, will work on it

**Comment by avsdev-cw** [comment]
Finally managed to get things fixed (missing dependency sigmund, npm required --unsafe-perm to run as root to install node-sass, ignore warning about bootstrap version)

Seems like the 2.10 branch is hugely indev (so much so the log-in substitution isn't working at the moment?).

Once I've fixed up the indev errors I'll look at making a 2.10 patch.

Out of interest whats the BC?

**Comment by thorsten** [comment]
It changes the template files, that's the BC.

**Comment by thorsten** [comment]
Any news on patching this against 3.0?

**Comment by thorsten** [comment]
No feedback.

**Pull request closed without merging**
