### PR TITLE
Added "View FAQ"

### PR DESCRIPTION
**Pull request by BrianPotter**
Users in my organization requested a way to view a FAQ after editing it without having to navigate through the website. I added a "View FAQ" button after the revision number in the Edit view.

### CODE REVIEW

**Comment by thorsten** [comment]
Is it possible to commit this one on the 2.10 branch?

**Comment by BrianPotter** [comment]
You bet!

**Comment by BrianPotter** [comment]
Ok. I think I committed it to the 2.10 branch, but also think I did it
wrong. Please let me know if I need to try again.

**Comment by thorsten** [comment]
Looks like there are a lot of commits from master in it. This will break everything. Please add the PR to the 2.10 branch, thanks in advance!

**Comment by BrianPotter** [comment]
Will do.

**Pull request closed without merging**
