### PR TITLE
Feature request: HTML-support for contactInformations

### PR DESCRIPTION
**Pull request by modelrailroader**
Hi Thorsten, 
this will add HTML-support for showing the contactInformations. It will insert a new configuration-item that can be checked if the contact informations should be formatted with HTML. 

The only problem which I see would be that the checkbox for this is not just underneath the text area for the contact-informations, but I didn't find a good solution for this. If you want to, you would have to check that again.

### CODE REVIEW

**Comment by thorsten** [comment]
Looks good, but the database update statement is missing in the update script and the Installer class. It would be cool if you could add this.

**Comment by modelrailroader** [comment]
Sorry, I absolutely forgot that. 
I'll add them tomorrow evening.

**Comment by thorsten** [comment]
Awesome, thanks in advance!

**Comment by thorsten** [comment]
Thanks a lot, great contribution!

**Pull request merged**
