### PR TITLE
Update language_pt-br.php

### PR DESCRIPTION
**Pull request by Broggio**
Added translation

### CODE REVIEW

**Comment by thorsten** [comment]
Is it possible to use the 2.9 branch?

**Comment by Broggio** [comment]
Yes i did to 2.9.4

**Comment by thorsten** [comment]
Okay, but the PR is against master branch

**Comment by thorsten** [comment]
Any news on this PR?

**Comment by Broggio** [comment]
Sorry, I do not understand

**Comment by thorsten** [comment]
Will merge it to master and backport it then. Thanks!

**Pull request merged**
