### PR TITLE
Twofactor-Authentification

### LINKED ISSUE #1090: Feature requests: 2FA
Small wishlist I thought I'd post. 

**Google Authenticator 2FA** - we all known how we have to keep moving forward with security. For external facing web authentication to me 2FA is a must have. Here's a php wrapper class for reference: https://github.com/PHPGangsta/GoogleAuthenticator

### PR DESCRIPTION
**Pull request by modelrailroader**
Take a look at this. This adds support for two-factor-authentification. I had some problems with implementating my 'old' code into your new UserAuthentification-Class, but should work like this. 
I used the lib we talked about "RobThree/TwoFactorAuth". I added some linkings in composer.json and composer.lock. 

What do you think about this?

I needed a bit time to dive into your code, but in the end, it was a lot of fun coding some things with php. 
Closes #1090

### CODE REVIEW

**Comment by modelrailroader** [comment]
I just see, that they are some problems with composer and the Code checks. I never worked with composer before. Maybe, you could take a look at it. 
And it wasn't possible to create the pull request in comparison to v.3.2.0-alpha

**Comment by thorsten** [comment]
wow, this is awesome! Thank you very much, I'll review it.

**Comment by thorsten** [comment]
It looks quite good, we have to add the database changes in the update script as well.

**Comment by thorsten** [comment]
> I just see, that they are some problems with composer and the Code checks. I never worked with composer before. Maybe, you could take a look at it.

This should be fixed by running `composer update` after rebasing to the current main branch

**Comment by modelrailroader** [comment]
I just corrected some things, could you review it again?

**Comment by thorsten** [comment]
awesome, thank you!

**Pull request merged**
