### PR TITLE
Adding kubernetes manifest samples

### PR DESCRIPTION
**Pull request by owndomainhome**
Those files, are samples about how implement deployment, service and ingress manifest for kubernetes environment.

### CODE REVIEW

**Comment by thorsten** [comment]
@owndomainhome wow, this looks good. Did you tried if it works?

**Comment by owndomainhome** [comment]
> @owndomainhome wow, this looks good. Did you tried if it works?

Yeah Sr. It works, i build my self in my Kubernetes Environments.

**Comment by owndomainhome** [comment]
I would appreciate approval of my contribution. Thanks!

**Comment by thorsten** [comment]
awesome, thank you very much!

**Comment by thorsten** [comment]
@owndomainhome would it be possible to add some documentation? Maybe somewhere here: https://github.com/thorsten/phpMyFAQ/blob/main/docs/installation.md

**Comment by owndomainhome** [comment]
> @owndomainhome would it be possible to add some documentation? Maybe somewhere here: https://github.com/thorsten/phpMyFAQ/blob/main/docs/installation.md

Ok i make it.

**Comment by owndomainhome** [comment]
> > @owndomainhome would it be possible to add some documentation? Maybe somewhere here: https://github.com/thorsten/phpMyFAQ/blob/main/docs/installation.md
> 
> Ok i make it.

@thorsten i added the doc lines!

**Comment by thorsten** [comment]
@owndomainhome did you create a new PR?

**Pull request merged**
