### PR TITLE
Issue #1937

### PR DESCRIPTION
**Pull request by thirdwheel**
- Definitions for ->fetchArray and ->fetchAll now match the DatabaseDriver instance
- Corrected case in Sqlsrv driver for nextId() function to match implemented instance

### CODE REVIEW

**Review by thorsten — CHANGES_REQUESTED** [review]
Looks good, could you please change this PR to the 3.0 branch. Then I can merge it into 3.0 and the main branch.

**Comment by thirdwheel** [comment]
Done.

**Comment by thirdwheel** [comment]
I think I did it wrong...

**Comment by thorsten** [comment]
Yes, you have to fix the issues in the 3.0 branch.

**Comment by thorsten** [comment]
I used your fixed here and mentioned you in the commit, thank you!

**Pull request closed without merging**
